#!/bin/tcsh

# This is a simple script which will carry out all of the basic steps
# required to make a MUFoldSS prediction. Note that it assumes that the
# following programs are in the appropriate directories:
# psiblast - PSIBLAST executable (from NCBI toolkit)


# The name of the BLAST data bank
set dbname = /home/chao/Desktop/UniRef50_Shrinked/uniref50_shrinked.fasta

# Where the NCBI programs have been installed
set ncbidir = /home/chao/Desktop/ncbi-blast-2.6.0+/bin

# Where the MUFoldSS programs have been installed
set execdir = /home/chao/Desktop/StandAlone/bin

# Where the MUFoldSS data files have been installed
set datadir = /home/chao/Desktop/StandAlone/data

set basename = $1:r
set rootname = $basename:t

# Generate a "unique" temporary filename root
set hostid = `hostid`
set tmproot = tmp$$$hostid

\cp -f $1 $tmproot.fasta

echo "Running PSI-BLAST with sequence" $1 "..."

$ncbidir/psiblast -num_iterations 3 -evalue 0.001 -db $dbname -query $tmproot.fasta -out_ascii_pssm $tmproot.profile

if ($status != 0) then
    tail $tmproot.profile
    echo "FATAL: Error whilst running psiblast - script terminated!"
    exit $status
endif

echo "Predicting secondary structure..."
python $execdir/executable.py -s $tmproot.fasta -p $tmproot.profile -wQ3 $datadir/modelQ3.h5 -wQ8 $datadir/modelQ8.h5 > $rootname.ss

if ($status != 0) then
    echo "FATAL: Error whilst running executable.py - script terminated!"
    exit $status
endif

# Remove temporary files

echo Cleaning up ...
\rm -f $tmproot.* error.log

echo "Final output files:" $rootname.ss
echo "Finished."
